server:
  port: 8080

spring:
  application:
    name: Ecommerce
  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_db

razorpay:
  keyId:
  keySecret:
  webhookSecret: secret_key_27



